"""add_explanations_column_to cds_recommendations

Revision ID: 3290f6f5f984
Revises: 9c4a2700bf39
Create Date: 2026-03-06 10:30:13.074386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3290f6f5f984'
down_revision: Union[str, None] = '9c4a2700bf39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ATTENDED', 'MISSED', 'CANCELLED', 'RESCHEDULED', name='appointmentstatus'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('SCHEDULED', 'ATTENDED', 'MISSED', 'CANCELLED', 'RESCHEDULED', name='appointmentstatus'),
               nullable=False)
    # ### end Alembic commands ###
