"""add missing visit columns

Revision ID: e97623584ab2
Revises: c586ee1ef2f9
Create Date: 2025-12-12 11:11:30.177397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97623584ab2'
down_revision: Union[str, None] = 'c586ee1ef2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types first
    op.execute("CREATE TYPE teststatus AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED')")
    
    op.create_table('cds_recommendations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('visit_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('recommended_medications', sa.JSON(), nullable=True),
    sa.Column('recommended_tests', sa.JSON(), nullable=True),
    sa.Column('risk_classification', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cds_recommendations_patient_id'), 'cds_recommendations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_cds_recommendations_visit_id'), 'cds_recommendations', ['visit_id'], unique=False)
    op.add_column('appointments', sa.Column('visit_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('appointments', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_appointments_visit_id'), 'appointments', ['visit_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'visits', ['visit_id'], ['id'])
    op.add_column('prescriptions', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('test_results', sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='teststatus'), nullable=False))
    op.add_column('test_results', sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('test_results', sa.Column('reference_range', sa.String(), nullable=True))
    op.add_column('test_results', sa.Column('code', sa.String(), nullable=True))
    op.add_column('test_results', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('test_results', sa.Column('investigation_data', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('chief_complaint', sa.String(), nullable=True))
    op.add_column('visits', sa.Column('complaints', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('symptoms', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('consultation', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('medical_history', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('social_history', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('physical_examination', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('investigations', sa.JSON(), nullable=True))
    op.add_column('visits', sa.Column('pulse', sa.Float(), nullable=True))
    op.add_column('visits', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('visits', sa.Column('spo2', sa.Float(), nullable=True))
    op.add_column('visits', sa.Column('pain_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'pain_score')
    op.drop_column('visits', 'spo2')
    op.drop_column('visits', 'temperature')
    op.drop_column('visits', 'pulse')
    op.drop_column('visits', 'investigations')
    op.drop_column('visits', 'physical_examination')
    op.drop_column('visits', 'social_history')
    op.drop_column('visits', 'medical_history')
    op.drop_column('visits', 'consultation')
    op.drop_column('visits', 'symptoms')
    op.drop_column('visits', 'complaints')
    op.drop_column('visits', 'chief_complaint')
    op.drop_column('test_results', 'investigation_data')
    op.drop_column('test_results', 'notes')
    op.drop_column('test_results', 'code')
    op.drop_column('test_results', 'reference_range')
    op.drop_column('test_results', 'observed_at')
    op.drop_column('test_results', 'status')
    op.drop_column('prescriptions', 'duration')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_visit_id'), table_name='appointments')
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'visit_id')
    op.drop_index(op.f('ix_cds_recommendations_visit_id'), table_name='cds_recommendations')
    op.drop_index(op.f('ix_cds_recommendations_patient_id'), table_name='cds_recommendations')
    op.drop_table('cds_recommendations')
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS teststatus")
    # ### end Alembic commands ###
